name: Build CV

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build CV
        uses: docker://texlive/texlive:latest
        with:
          args: xelatex /github/workspace/cv.tex

      - name: Update markdown version
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install openai
          python update_markdown.py

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github@github.com"
          git add -A
          git commit -m "build CV [skip ci]" || echo "No changes to commit"
          git push origin master
